DROP TABLE IF EXISTS SALES;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE SALES (
    SALE_ID INTEGER PRIMARY KEY,
    PRODUCT_ID INTEGER NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL,
    STORE VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID INTEGER PRIMARY KEY,
    PRODUCT_DESCRIPTION VARCHAR(255) NOT NULL,
    PRODUCT_PRICE INTEGER NOT NULL
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    CUSTOMER_SURNAME VARCHAR(255) NOT NULL
);

INSERT INTO SALES(SALE_ID, PRODUCT_ID, CUSTOMER_ID, QUANTITY, STORE) VALUES (1, 4, 1, 3, 'STORE1');
INSERT INTO SALES(SALE_ID, PRODUCT_ID, CUSTOMER_ID, QUANTITY, STORE) VALUES (2, 6, 1, 5, 'STORE1');
INSERT INTO SALES(SALE_ID, PRODUCT_ID, CUSTOMER_ID, QUANTITY, STORE) VALUES (3, 7, 2, 2, 'STORE3');
INSERT INTO SALES(SALE_ID, PRODUCT_ID, CUSTOMER_ID, QUANTITY, STORE) VALUES (4, 8, 3, 1, 'STORE2');

INSERT INTO PRODUCTS(PRODUCT_ID, PRODUCT_DESCRIPTION, PRODUCT_PRICE) VALUES (4, 'PRODUCT4', 10);
INSERT INTO PRODUCTS(PRODUCT_ID, PRODUCT_DESCRIPTION, PRODUCT_PRICE) VALUES (6, 'PRODUCT6', 15);
INSERT INTO PRODUCTS(PRODUCT_ID, PRODUCT_DESCRIPTION, PRODUCT_PRICE) VALUES (7, 'PRODUCT7', 12);
INSERT INTO PRODUCTS(PRODUCT_ID, PRODUCT_DESCRIPTION, PRODUCT_PRICE) VALUES (8, 'PRODUCT8', 11);

INSERT INTO CUSTOMERS(CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_SURNAME) VALUES (1, 'NAME1', 'SURNAME1');
INSERT INTO CUSTOMERS(CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_SURNAME) VALUES (2, 'NAME2', 'SURNAME2');
INSERT INTO CUSTOMERS(CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_SURNAME) VALUES (3, 'NAME3', 'SURNAME3');
